

GET http://localhost:3333 
Content-Type: application/json

###

POST http://localhost:3333 
Content-Type: application/json


{
    "name": "Pizza doce",
    "description":"pizza com recheio de banana e chocolate",
    "hourCreated": "23:00",
    "dateCreated": "12/02/2015",
    "inDiet":       "NAO"
}   

###
GET http://localhost:3333/ab8e2dd7-a606-4fc4-b4a7-c6471407fd68
Content-Type: application/json

###
PUT  http://localhost:3333/ab8e2dd7-a606-4fc4-b4a7-c6471407fd68
Content-Type: application/json

{
  "name": "Pão com ovo",
  "description": "Refeição da manhã",
  "hourCreated": "08:00",
  "dateCreated": "2023/12/10",
  "inDiet": "NAO"
}