

GET http://localhost:3333/diets
Content-Type: application/json

###

POST http://localhost:3333 
Content-Type: application/json


{
    "name": "Pizza doce",
    "description":"pizza com recheio de banana e chocolate",
    "hourCreated": "23:00",
    "dateCreated": "12/02/2015",
    "inDiet":       "NAO"
}   

###
GET http://localhost:3333/diets/65dac10f-f6f7-4819-a476-15df5ffc819f
Content-Type: application/json

###
PUT  http://localhost:3333/ab8e2dd7-a606-4fc4-b4a7-c6471407fd68
Content-Type: application/json

{
  "name": "Pão com ovo",
  "description": "Refeição da manhã",
  "hourCreated": "08:00",
  "dateCreated": "2023/12/10",
  "inDiet": "NAO"
}

###

GET http://localhost:3333/diets/stats/in-diet

###

GET http://localhost:3333/diets/stats/out-diet

###

GET http://localhost:3333/diets/stats/total

###

GET http://localhost:3333/diets/sequence/in-diet

###

GET http://localhost:3333/diets/sequence/out-diet

###

GET http://localhost:3333/diets/ordered



app.get("/diets/stats/in-diet", SimDiet);      // Refeições dentro da dieta
  app.get("/diets/stats/out-diet", NaoDiet);     // Refeições fora da dieta
  app.get("/diets/stats/total", AllDiet);        // Total de refeições

  // Rotas de sequência e ordenação
  app.get("/diets/sequence/in-diet", getInDietSequence);    // Sequência na dieta
  app.get("/diets/sequence/out-diet", getNotInDietSequence); // Sequência fora da dieta
  app.get("/diets/ordered", OrderByDate);  